class ListMedicines {
  List<String> _medicines = [
    "Ácido acetil salicílico (AAS)-100mg",
    "Adenosina (Adenocard) 6mg/2ml",
    "Adrenalina (Epinefrina) 1mg/ml",
    "Aminofilina 24mg/10ml",
    "Amiodarona (ancoron) 50mg/3ml",
    "Atropina 0,25mg/1ml",
    "Bicarbonato de Sódio 8,4%-10ml",
    "Brometo de fenoterol 0,5% (berotec) gts",
    "Brometo de Ipratróprio 0,25mg (atrovent) gts",
    "Brometo de Suxametônio (Succitrat) 100mg",
    "Bromoprida (digesan)5mg/ml",
    "Buscopam composto amp",
    "Captopril (Capoten) 12,5 mg",
    "Captopril (Capoten) 25 mg",
    "Captopril (Capoten) 50 mg",
    "Carvão Ativado 250 mg",
    "Cetoprofeno (profenid) 100mg (IV)",
    "Cetoprofeno (profenid) 50mg/ml (IM)",
    "Clonidina (atensina) 0,1mg comp",
    "Clopidogrel (plavix) 75 mg comp",
    "Cloreto de potássio (KCl) a 10%",
    "Cloreto de Sódio (NaCl) a 20%",
    "Cloridrato de Cetamina",
    "Complexo B-2ml",
    "Deslanosídeo (cedilanide)0,2 mg",
    "Dexametasona (Decadron) 4 mg/ml",
    "Diazepam 10 mg comp",
    "Diazepam 10 mg/ml",
    "Diazepam 5 mg comp",
    "Diazepam 5mg/ml",
    "Diclofenaco potássico (cataflan) 75 mg/3ml",
    "Diclofenaco sódico (Voltarem)75 mg/3ml",
    "Dimenidrinato (dramin) 100mg comp",
    "Dinitrato de isossorbida (isordil) 5mg comp",
    "Dipirona 500 mg/ml 10 ml gts",
    "Dipirona 500 mg/ml 2 ml",
    "Dobutamina (Dobutrex) 12,5 mg/ml - 10 ml",
    "Dopamina 5mg/ml-10ml",
    "Fenitoína 50 mg/ml",
    "Fenobarbital 100mg/2ml",
    "Fentanil 0,05 mg/ml",
    "Flumazenil 0,1 mg/ml",
    "Furosemida (Lasix) 10mg/2ml",
    "Glicose a 25% 10ml",
    "Glicose a 50% 10 ml",
    "Gluconato de Cálcio a 10%-10ml",
    "Haloperidol 5 mg/ml",
    "Hidralazina (apresolina) 200mg/ml",
    "Hidrocortisona 100 mg (androcortil)",
    "Hidrocortisona 500 mg (androcortil)",
    "Hioscina (buscopam) 20mg/ml",
    "Lidocaína 2% 5ml (sem vasoconstritor)",
    "Lidocaína 2% com vasoconstritor",
    "Manitol 20% 250ml",
    "Meperidina 50mg/ml",
    "Metoclopramida (plasil) 10 mg 2 ml",
    "Metoclopramida (plasil) gts",
    "Metoprolol 5mg (seringa)",
    "Midazolam 5 mg/ml",
    "Naloxona (narcan) 0,4mg/ml",
    "Nitroglicerina venosa (tridil)5mg/ml",
    "Nitroprussiato de sódio (nipride) 50 mg",
    "Noradrenalina 4mg/ml",
    "Omeprazol 40 mg amp",
    "Ondansetrona (zofran) 4mg/ml",
    "Prometazina (fenergan) 25mg-2ml",
    "Ranitidina (antak/vonal) 25mg/ml",
    "Salbutamol (aerolin) aerossol",
    "Solução fisiológica a 0,9% 500ml",
    "Solução glicosada a 5% 500ml",
    "Solução Ringer Lactato 500 ml",
    "Solumedrol 40 mg",
    "Sulfato de Magnésio 1 mEq/ml - 10 ml",
    "Sulfato de morfina (dimorf) 10 mg/ml",
    "Tenoxican (tiltatil) 40 mg",
    "Tiamina (vit B1) 10 mg/ml",
    "Tramadol (tramal) 50mg/ml",
    "Trometamina 30 mg/ml",
    "Vasopressina (encrise)30 mg/ml",
    "Vitamina C ampola",
    "Vitamina K 100 mg/ml",
  ];

  List<String> _route = [
    "Oral",
    "Sublingual",
    "Intramuscular",
    "Subcutânea",
  ];

  List<String> get medicines {
    return this._medicines;
  }

  List<String> get route {
    return this._route;
  }
}
